# Generated by Django 4.1.5 on 2023-02-02 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, default='empty', max_length=50)),
                ('lastname', models.CharField(blank=True, default='empty', max_length=50)),
                ('phone_number', models.IntegerField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, default='empty', help_text='example@example.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('avenue', models.CharField(max_length=50)),
                ('plate', models.IntegerField(max_length=3)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
