# Generated by Django 4.1.5 on 2023-02-09 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('type', models.CharField(choices=[('P', 'Percent'), ('C', 'Cash')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(blank=True, default='empty', max_length=20)),
                ('status', models.CharField(choices=[('E', 'Exist'), ('F', 'Finish')], max_length=1)),
                ('information', models.TextField(blank=True, default='empty')),
                ('cost', models.FloatField()),
                ('categories', models.ManyToManyField(to='products.category')),
                ('discounts', models.ManyToManyField(blank=True, to='products.discount')),
            ],
        ),
    ]
