# Generated by Django 4.1.5 on 2023-02-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Paied'), ('U', 'Unpaied')], default='U', max_length=1),
            preserve_default=False,
        ),
    ]
