# Generated by Django 4.1.5 on 2023-02-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount_id',
            new_name='discounts',
        ),
    ]
