# Generated by Django 4.1.5 on 2023-02-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_category_id_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='product.discount'),
        ),
    ]
